### ISSUE TITLE
pageview 是不能用吗

### ISSUE THREAD

**Issue by zhangweihong** [wilin52/union_tabs#2]

**Comment by wilin52** [comment]
pageview 将实现都封闭在内部，无法支持nested 功能，所以移植了pageview 代码

**Comment by zhangweihong** [comment]
有什么思路实现pageview的嵌套吗 最近这2天在思考这个问题 尝试着做下

**Comment by wilin52** [comment]
@zhangweihong 一般嵌套都用tabbarview吧，不过不支持联动

**Comment by zhangweihong** [comment]
好吧 自己琢磨半天写了一个  暂时能用 [https://blog.csdn.net/u011866450/article/details/108341257](url)

**Comment by zhangweihong** [comment]
好吧 自己琢磨半天写一个 不过 有点不理想 暂时可用

https://blog.csdn.net/u011866450/article/details/108341257
