### ISSUE TITLE
升级flutter1.22问题

### ISSUE THREAD

**Issue by shaohui93** [wilin52/union_tabs#3]
UnionInnerScrollableState这个类少了ScrollContext.saveOffset 这个实现

**Comment by wilin52** [comment]
已经修复，升级到1.0.0+5 就好了

**Comment by shaohui93** [comment]
../../fluttersdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/union_tabs-1.0.0+5/lib/src/inner/union_inner_scrollable.dart:262:7: Error: The non-abstract class 'UnionInnerScrollableState' is missing implementations for these members:
 - ScrollContext.saveOffset
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class UnionInnerScrollableState extends State<UnionInnerScrollable>
      ^^^^^^^^^^^^^^^^^^^^^^^^^
../../fluttersdk/flutter/packages/flutter/lib/src/widgets/scroll_context.dart:72:8: Context: 'ScrollContext.saveOffset' is defined here.
  void saveOffset(double offset);
       ^^^^^^^^^^


FAILURE: Build failed with an exception.


union_tabs: ^1.0.0+5这个版本在flutter1.22上还会出现这个问题

**Comment by wilin52** [comment]
> ../../fluttersdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/union_tabs-1.0.0+5/lib/src/inner/union_inner_scrollable.dart:262:7: Error: The non-abstract class 'UnionInnerScrollableState' is missing implementations for these members:
> 
> * ScrollContext.saveOffset
>   Try to either
> * provide an implementation,
> * inherit an implementation from a superclass or mixin,
> * mark the class as abstract, or
> * provide a 'noSuchMethod' implementation.
> 
> class UnionInnerScrollableState extends State
> ^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../fluttersdk/flutter/packages/flutter/lib/src/widgets/scroll_context.dart:72:8: Context: 'ScrollContext.saveOffset' is defined here.
> void saveOffset(double offset);
> ^^^^^^^^^^
> 
> FAILURE: Build failed with an exception.
> 
> union_tabs: ^1.0.0+5这个版本在flutter1.22上还会出现这个问题

是的，这个问题最近做个适配

**Comment by wilin52** [comment]
> ../../fluttersdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/union_tabs-1.0.0+5/lib/src/inner/union_inner_scrollable.dart:262:7: Error: The non-abstract class 'UnionInnerScrollableState' is missing implementations for these members:
> 
> * ScrollContext.saveOffset
>   Try to either
> * provide an implementation,
> * inherit an implementation from a superclass or mixin,
> * mark the class as abstract, or
> * provide a 'noSuchMethod' implementation.
> 
> class UnionInnerScrollableState extends State
> ^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../fluttersdk/flutter/packages/flutter/lib/src/widgets/scroll_context.dart:72:8: Context: 'ScrollContext.saveOffset' is defined here.
> void saveOffset(double offset);
> ^^^^^^^^^^
> 
> FAILURE: Build failed with an exception.
> 
> union_tabs: ^1.0.0+5这个版本在flutter1.22上还会出现这个问题

1.0.0+7 已经修复🌹

**Comment by wilin52** [comment]
已经修复，关闭issue
